package main

const (
	_service     string = "config"
	_serviced           = _service /*+ "d"*/
	_SERVICE     string = "CONFIG"
	_SERVICED           = _SERVICE /*+ "D"*/
	_hash_Size   int    = 512 / 8
	_passwd_Z    string = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
	_passwd_z    string = "abcdefghijklmnopqrstuvwxyz"
	_passwd_0    string = "0123456789"
	_passwd_oops string = "_" // carefully with a special symbols
	_passwd             = _passwd_Z + _passwd_z + _passwd_0 + _passwd_oops
	_next_IDName _Name  = "next_ID"
	_next_ID     _ID    = 0

	_W_AS                                               _Action       = "AS"
	_W_ID                                               _Action       = "ID"
	_W_PUBLIC                                           _Action       = "OUTER_LIST"
	_W_accept                                           _Action       = "accept"
	_W_access                                           _Action       = "access"
	_W_access__internal                                               = _W_access + "-" + _W_internal
	_W_add                                              _Action       = "add"
	_W_address                                          _Action       = "address"
	_W_address__book                                                  = _W_address + "-" + _W_book
	_W_address__set                                                   = _W_address + "-" + _W_set
	_W_aggregate                                        _Action       = "aggregate"
	_W_ah                                               _Action       = "ah"
	_W_all                                              _Action       = "all"
	_W_any                                              _Action       = "any"
	_W_any__service                                                   = _W_any + "-" + _W_service
	_W_application                                      _Action       = "application"
	_W_applications                                                   = _W_application + "s"
	_W_applications____application                                    = _W_applications + " " + _W_application
	_W_arp                                              _Action       = "arp"
	_W_balance                                          _Action       = "balance"
	_W_bgp                                              _Action       = "bgp"
	_W_book                                             _Action       = "book"
	_W_bootp                                            _Action       = "bootp"
	_W_deny                                             _Action       = "deny"
	_W_deny__all                                                      = _W_deny + "-" + _W_all
	_W_destination                                      _Action       = "destination"
	_W_destination__address                                           = _W_destination + "-" + _W_address
	_W_destination__address__name                                     = _W_destination__address + "-" + _W_name
	_W_destination__nat                                               = _W_destination + "-" + _W_nat
	_W_destination__port                                              = _W_destination + "-" + _W_port
	_W_destination__prefix__list                                      = _W_destination + "-" + _W_prefix__list
	_W_dhcp                                             _Action       = "dhcp"
	_W_dhcpv6                                                         = _W_dhcp + _W_v6
	_W_direct                                           _Action       = "direct"
	_W_discard                                          _Action       = "discard"
	_W_dns                                              _Action       = "dns"
	_W_dns__name                                                      = _W_dns + "-" + _W_name
	_W_egp                                              _Action       = "egp"
	_W_esp                                              _Action       = "esp"
	_W_exact                                            _Action       = "exact"
	_W_export                                           _Action       = "export"
	_W_export_metric                                                  = _W_export + "_" + _W_metric
	_W_external                                         _Action       = "external"
	_W_filter                                           _Action       = "filter"
	_W_firewall                                         _Action       = "firewall"
	_W_firewall___filter                                              = _W_firewall + " " + _W_filter
	_W_fqdn                                             _Action       = "fqdn"
	_W_from                                             _Action       = "from"
	_W_from___zone                                                    = _W_from + " " + _W_zone
	_W_from__zone                                                     = _W_from + "-" + _W_zone
	_W_fxp                                              _Action       = "fxp"
	_W_fxp0                                                           = _W_fxp + "0"
	_W_fxp0_0                                                         = _W_fxp0 + ".0"
	_W_global                                           _Action       = "global"
	_W_gr                                               _Action       = "gr"
	_W_gr0                                                            = _W_gr + "0"
	_W_gre                                              _Action       = "gre"
	_W_group                                            _Action       = "group"
	_W_hop                                              _Action       = "hop"
	_W_host                                             _Action       = "host"
	_W_host__inbound__traffic                                         = _W_host + "-" + _W_inbound + "-" + _W_traffic
	_W_icmp                                             _Action       = "icmp"
	_W_icmp6                                                          = _W_icmp + "6"
	_W_igmp                                             _Action       = "igmp"
	_W_ike                                              _Action       = "ike"
	_W_import                                           _Action       = "import"
	_W_import_metric                                                  = _W_import + "_" + _W_metric
	_W_inbound                                          _Action       = "inbound"
	_W_instance                                         _Action       = "instance"
	_W_interface                                        _Action       = "interface"
	_W_interfaces                                                     = _W_interface + "s"
	_W_internal                                         _Action       = "internal"
	_W_ip                                               _Action       = "ip"
	_W_ipip                                                           = _W_ip + _W_ip
	_W_ipprefix                                                       = _W_ip + _W_prefix
	_W_junos                                            _Action       = "junos"
	_W_junos__host                                                    = _W_junos + "-" + _W_host
	_W_link                                             _Action       = "link"
	_W_list                                             _Action       = "list"
	_W_lo                                               _Action       = "lo"
	_W_lo0                                                            = _W_lo + "0"
	_W_lo0_0                                                          = _W_lo0 + ".0"
	_W_load                                             _Action       = "load"
	_W_load__balance                                                  = _W_load + "-" + _W_balance
	_W_local                                            _Action       = "local"
	_W_log                                              _Action       = "log"
	_W_longer                                           _Action       = "longer"
	_W_lt                                               _Action       = "lt"
	_W_lt0                                                            = _W_lt + "0"
	_W_mapped                                           _Action       = "mapped"
	_W_mapped__port                                                   = _W_mapped + "-" + _W_port
	_W_master                                           _Action       = "master"
	_W_metric                                           _Action       = "metric"
	_W_mgmt                                             _Action       = "mgmt"
	_W_mgmt_junos                                                     = _W_mgmt + "_" + _W_junos
	_W_name                                             _Action       = "name"
	_W_nat                                              _Action       = "nat"
	_W_neighbor                                         _Action       = "neighbor"
	_W_next                                             _Action       = "next"
	_W_next__hop                                                      = _W_next + "-" + _W_hop
	_W_next__table                                                    = _W_next + "-" + _W_table
	_W_options                                          _Action       = "options"
	_W_or                                               _Action       = "or"
	_W_orlonger                                                       = _W_or + _W_longer
	_W_ospf                                             _Action       = "ospf"
	_W_packet                                           _Action       = "packet"
	_W_per                                              _Action       = "per"
	_W_per__packet                                                    = _W_per + "-" + _W_packet
	_W_permit                                           _Action       = "permit"
	_W_permit__all                                                    = _W_permit + "-" + _W_all
	_W_pim                                              _Action       = "pim"
	_W_ping                                             _Action       = "ping"
	_W_policies                                         _Action       = "policies"
	_W_policy                                           _Action       = "policy"
	_W_policy__options                                                = _W_policy + "-" + _W_options
	_W_policy__options___policy__statement                            = _W_policy__options + " " + _W_policy__statement
	_W_policy__options___prefix__list                                 = _W_policy__options + " " + _W_prefix__list
	_W_policy__statement                                              = _W_policy + "-" + _W_statement
	_W_pool                                             _Action       = "pool"
	_W_port                                             _Action       = "port"
	_W_preference                                       _Action       = "preference"
	_W_prefix                                           _Action       = "prefix"
	_W_prefix__list                                                   = _W_prefix + "-" + _W_list
	_W_prefix__list__filter                                           = _W_prefix__list + "-" + _W_filter
	_W_prefix__name                                                   = _W_prefix + "-" + _W_name
	_W_protocol                                         _Action       = "protocol"
	_W_protocols                                                      = _W_protocol + "s"
	_W_protocols___bgp                                                = _W_protocols + " " + _W_bgp
	_W_proxy                                            _Action       = "proxy"
	_W_proxy__arp                                                     = _W_proxy + "-" + _W_arp
	_W_ptmp                                             _Action       = "ptmp"
	_W_ptp                                              _Action       = "ptp"
	_W_qnh                                              _Action       = "qnh"
	_W_qualified                                        _Action       = "qualified"
	_W_qualified__next__hop                                           = _W_qualified + "-" + _W_next__hop
	_W_redistribute                                     _Action       = "redistribute"
	_W_reject                                           _Action       = "reject"
	_W_route                                            _Action       = "route"
	_W_route__type                                                    = _W_route + "-" + _W_type
	_W_routing                                          _Action       = "routing"
	_W_routing__group                                                 = _W_routing + "-" + _W_group
	_W_routing__instance                                              = _W_routing + "-" + _W_instance
	_W_routing__instances                                             = _W_routing__instance + "s"
	_W_rsvp                                             _Action       = "rsvp"
	_W_rule                                             _Action       = "rule"
	_W_rule__set                                                      = _W_rule + "-" + _W_set
	_W_sctp                                             _Action       = "sctp"
	_W_security                                         _Action       = "security"
	_W_security___address__book                                       = _W_security + " " + _W_address__book
	_W_security___address__book___global                              = _W_security___address__book + " " + _W_global
	_W_security___address__book___global___address                    = _W_security___address__book___global + " " + _W_address
	_W_security___address__book___global___address__set               = _W_security___address__book___global + " " + _W_address__set
	_W_security___nat                                                 = _W_security + " " + _W_nat
	_W_security___nat___destination                                   = _W_security___nat + " " + _W_destination
	_W_security___nat___proxy__arp                                    = _W_security___nat + " " + _W_proxy__arp
	_W_security___nat___source                                        = _W_security___nat + " " + _W_source
	_W_security___nat___static                                        = _W_security___nat + " " + _W_static
	_W_security___policies                                            = _W_security + " " + _W_policies
	_W_security___policies___global                                   = _W_security___policies + " " + _W_global
	_W_security___policies___global___policy                          = _W_security___policies___global + " " + _W_security___policy
	_W_security___policy                                              = _W_security + " " + _W_policy
	_W_security__zone                                                 = _W_security + "-" + _W_zone
	_W_security__zones                                                = _W_security__zone + "s"
	_W_security__zones___security__zone                               = _W_security__zones + " " + _W_security__zone
	_W_self                                             _Action       = "self"
	_W_service                                          _Action       = "service"
	_W_set                                              _Action       = "set"
	_W_snmp                                             _Action       = "snmp"
	_W_snmp__trap                                                     = _W_snmp + "-" + _W_trap
	_W_source                                           _Action       = "source"
	_W_source__address                                                = _W_source + "-" + _W_address
	_W_source__address__name                                          = _W_source__address + "-" + _W_name
	_W_source__nat                                                    = _W_source + "-" + _W_nat
	_W_source__port                                                   = _W_source + "-" + _W_port
	_W_source__prefix__list                                           = _W_source + "-" + _W_prefix__list
	_W_ssh                                              _Action       = "ssh"
	_W_st                                               _Action       = "st"
	_W_st0                                                            = _W_st + "0"
	_W_statement                                        _Action       = "statement"
	_W_static                                           _Action       = "static"
	_W_static___route                                                 = _W_static + " " + _W_route
	_W_static__nat                                                    = _W_static + "-" + _W_nat
	_W_table                                            _Action       = "table"
	_W_tcp                                              _Action       = "tcp"
	_W_term                                             _Action       = "term"
	_W_then                                             _Action       = "then"
	_W_to                                               _Action       = "to"
	_W_to___zone                                                      = _W_to + " " + _W_zone
	_W_to__zone                                                       = _W_to + "-" + _W_zone
	_W_trace                                            _Action       = "trace"
	_W_traceroute                                                     = _W_trace + _W_route
	_W_traffic                                          _Action       = "traffic"
	_W_trap                                             _Action       = "trap"
	_W_type                                             _Action       = "type"
	_W_udp                                              _Action       = "udp"
	_W_v4                                               _Action       = "v4"
	_W_v6                                               _Action       = "v6"
	_W_vi                                               _Action       = "vi"
	_W_zone                                             _Action       = "zone"
	_W_zones                                                          = _W_zone + "s"
	_Communication_ptmp                                               = _Communication(_W_ptmp)
	_Communication_ptp                                                = _Communication(_W_ptp)
	_Mask_exact                                                       = _Mask(_W_exact)
	_Mask_longer                                                      = _Mask(_W_longer)
	_Mask_orlonger                                                    = _Mask(_W_orlonger)
	_Name_AS                                                          = _Name(_W_AS)
	_Name_ID                                                          = _Name(_W_ID)
	_Name_PUBLIC                                                      = _Name(_W_PUBLIC)
	_Name_any                                                         = _Name(_W_any)
	_Name_fxp0                                                        = _Name(_W_fxp0)
	_Name_fxp0_0                                                      = _Name(_W_fxp0_0)
	_Name_gr0                                                         = _Name(_W_gr0)
	_Name_junos__host                                                 = _Name(_W_junos__host)
	_Name_lo0                                                         = _Name(_W_lo0)
	_Name_lo0_0                                                       = _Name(_W_lo0_0)
	_Name_lt0                                                         = _Name(_W_lt0)
	_Name_master                                                      = _Name(_W_master)
	_Name_mgmt__junos                                                 = _Name(_W_mgmt_junos)
	_Name_st0                                                         = _Name(_W_st0)
	_Protocol_access__internal                                        = _Protocol(_W_access__internal)
	_Protocol_aggregate                                               = _Protocol(_W_aggregate)
	_Protocol_ah                                                      = _Protocol(_W_ah)
	_Protocol_all                                                     = _Protocol(_W_all)
	_Protocol_arp                                                     = _Protocol(_W_arp)
	_Protocol_bgp                                                     = _Protocol(_W_bgp)
	_Protocol_direct                                                  = _Protocol(_W_direct)
	_Protocol_egp                                                     = _Protocol(_W_egp)
	_Protocol_esp                                                     = _Protocol(_W_esp)
	_Protocol_gre                                                     = _Protocol(_W_gre)
	_Protocol_icmp                                                    = _Protocol(_W_icmp)
	_Protocol_icmp6                                                   = _Protocol(_W_icmp6)
	_Protocol_igmp                                                    = _Protocol(_W_igmp)
	_Protocol_ipip                                                    = _Protocol(_W_ipip)
	_Protocol_local                                                   = _Protocol(_W_local)
	_Protocol_ospf                                                    = _Protocol(_W_ospf)
	_Protocol_pim                                                     = _Protocol(_W_pim)
	_Protocol_rsvp                                                    = _Protocol(_W_rsvp)
	_Protocol_sctp                                                    = _Protocol(_W_sctp)
	_Protocol_static                                                  = _Protocol(_W_static)
	_Protocol_tcp                                                     = _Protocol(_W_tcp)
	_Protocol_udp                                                     = _Protocol(_W_udp)
	_Route_Weight_bits_per_rm                           _Route_Weight = 2
	_Route_Weight_max_rm                                              = 32/_Route_Weight_bits_per_rm - 1
	_Service_all                                                      = _Service(_W_all)
	_Service_any__service                                             = _Service(_W_any__service)
	_Service_bootp                                                    = _Service(_W_bootp)
	_Service_dhcp                                                     = _Service(_W_dhcp)
	_Service_dhcpv6                                                   = _Service(_W_dhcpv6)
	_Service_ike                                                      = _Service(_W_ike)
	_Service_ping                                                     = _Service(_W_ping)
	_Service_snmp                                                     = _Service(_W_snmp)
	_Service_snmp_trap                                                = _Service(_W_snmp__trap)
	_Service_ssh                                                      = _Service(_W_ssh)
	_Service_traceroute                                               = _Service(_W_traceroute)
	_Type_destination                                                 = _Type(_W_destination)
	_Type_exact                                                       = _Type(_W_exact)
	_Type_external                                                    = _Type(_W_external)
	_Type_firewall                                                    = _Type(_W_firewall)
	_Type_fqdn                                                        = _Type(_W_fqdn)
	_Type_from                                                        = _Type(_W_from)
	_Type_fxp                                                         = _Type(_W_fxp)
	_Type_global                                                      = _Type(_W_global)
	_Type_gr                                                          = _Type(_W_gr)
	_Type_internal                                                    = _Type(_W_internal)
	_Type_ipprefix                                                    = _Type(_W_ipprefix)
	_Type_lo                                                          = _Type(_W_lo)
	_Type_lt                                                          = _Type(_W_lt)
	_Type_policy__statement                                           = _Type(_W_policy__statement)
	_Type_pool                                                        = _Type(_W_pool)
	_Type_set                                                         = _Type(_W_set)
	_Type_source                                                      = _Type(_W_source)
	_Type_st                                                          = _Type(_W_st)
	_Type_static                                                      = _Type(_W_static)
	_Type_then                                                        = _Type(_W_then)
	_Type_to                                                          = _Type(_W_to)

	_group                _Default = "settings_group"
	_loglevel             _Default = "settings_loglevel"
	_sp_default_policy    _Default = "settings_sp_efault_policy"
	_comm_if              _Default = "settings_comm_if"
	_comm_vi              _Default = "settings_comm_vi"
	_VI_IPPrefix          _Default = "settings_VI_IPprefix"
	_VI_IPShift           _Default = "settings_VI_IPshift"
	_RI                   _Default = "settings_RI"
	_mgmt_RI              _Default = "settings_mgmt_RI"
	_mgmt_IF              _Default = "settings_mgmt_IF"
	_host_RI              _Default = "settings_host_RI"
	_mgmt_Description     _Default = "settings_mgmt_description"
	_domain_name          _Default = "settings_domain_name"
	_GT_list              _Default = "settings_GT_list"
	_dirname_GT           _Default = "settings_path_GT"
	_dirname_out          _Default = "settings_path_out"
	_filename_host_list   _Default = "settings_filename_host_list"
	_filename_list_config _Default = "settings_files_config"
	// _Route_Weight_bits_per_rm       _Default = "settings_Route_Weight_bits_per_rm"
	// _Route_Weight_max_rm           _Default = "settings_Route_Weight_max_rm"
)
