package main

const (
	_service     string = "config"
	_serviced           = _service /*+ "d"*/
	_SERVICE     string = "CONFIG"
	_SERVICED           = _SERVICE /*+ "D"*/
	_hash_Size   int    = 512 / 8
	_passwd_Z    string = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
	_passwd_z    string = "abcdefghijklmnopqrstuvwxyz"
	_passwd_0    string = "0123456789"
	_passwd_oops string = "_" // carefully with a special symbols
	_passwd             = _passwd_Z + _passwd_z + _passwd_0 + _passwd_oops
	_next_IDName _Name  = "next_ID"
	_next_ID     _ID    = 0

	_Action_accept                                           _Action        = "accept"
	_Action_add                                              _Action        = "add"
	_Action_address                                          _Action        = "address"
	_Action_address__book                                                   = _Action_address + "-" + _Action_book
	_Action_address__set                                                    = _Action_address + "-" + _Action_set
	_Action_aggregate                                                       = _Action(_Protocol_aggregate)
	_Action_all                                              _Action        = "all"
	_Action_application                                      _Action        = "application"
	_Action_applications                                                    = _Action_application + "s"
	_Action_applications____application                                     = _Action_applications + " " + _Action_application
	_Action_bgp                                                             = _Action(_Protocol_bgp)
	_Action_book                                             _Action        = "book"
	_Action_deny                                             _Action        = "deny"
	_Action_deny__all                                                       = _Action_deny + "-" + _Action_all
	_Action_destination                                      _Action        = "destination"
	_Action_destination__address                                            = _Action_destination + "-" + _Action_address
	_Action_destination__address__name                                      = _Action_destination__address + "-" + _Action_name
	_Action_destination__nat                                                = _Action_destination + "-" + _Action_nat
	_Action_destination__port                                               = _Action_destination + "-" + _Action_port
	_Action_destination__prefix__list                                       = _Action_destination + "-" + _Action_prefix__list
	_Action_discard                                          _Action        = "discard"
	_Action_dns                                              _Action        = "dns"
	_Action_dns__name                                                       = _Action_dns + "-" + _Action_name
	_Action_exact                                            _Action        = "exact"
	_Action_export                                           _Action        = "export"
	_Action_export_metric                                                   = _Action_export + "_" + _Action_metric
	_Action_filter                                           _Action        = "filter"
	_Action_firewall                                                        = _Action(_Type_firewall)
	_Action_firewall___filter                                               = _Action_firewall + " " + _Action_filter
	_Action_fqdn                                             _Action        = "fqdn"
	_Action_from                                             _Action        = "from"
	_Action_from___zone                                                     = _Action_from + " " + _Action_zone
	_Action_from__zone                                                      = _Action_from + "-" + _Action_zone
	_Action_fxp                                              _Action        = "fxp"
	_Action_global                                           _Action        = "global"
	_Action_gr                                               _Action        = "gr"
	_Action_group                                            _Action        = "group"
	_Action_hop                                              _Action        = "hop"
	_Action_host_inbound_traffic                             _Action        = "host-inbound-traffic"
	_Action_import                                           _Action        = "import"
	_Action_import_metric                                                   = _Action_import + "_" + _Action_metric
	_Action_instance                                         _Action        = "instance"
	_Action_interface                                        _Action        = "interface"
	_Action_interfaces                                                      = _Action_interface + "s"
	_Action_ipprefix                                         _Action        = "ipprefix"
	_Action_link                                             _Action        = "link"
	_Action_list                                             _Action        = "list"
	_Action_lo                                                              = _Action(_Type_lo)
	_Action_load_balance                                     _Action        = "load-balance"
	_Action_log                                              _Action        = "log"
	_Action_lt                                                              = _Action(_Type_lt)
	_Action_mapped                                           _Action        = "mapped"
	_Action_mapped__port                                                    = _Action_mapped + "-" + _Action_port
	_Action_metric                                           _Action        = "metric"
	_Action_name                                             _Action        = "name"
	_Action_nat                                              _Action        = "nat"
	_Action_neighbor                                         _Action        = "neighbor"
	_Action_next                                             _Action        = "next"
	_Action_next__hop                                                       = _Action_next + "-" + _Action_hop
	_Action_next__table                                                     = _Action_next + "-" + _Action_table
	_Action_options                                          _Action        = "options"
	_Action_per__packet                                      _Action        = "per-packet"
	_Action_permit                                           _Action        = "permit"
	_Action_permit__all                                                     = _Action_permit + "-" + _Action_all
	_Action_policies                                         _Action        = "policies"
	_Action_policy                                           _Action        = "policy"
	_Action_policy__options                                                 = _Action_policy + "-" + _Action_options
	_Action_policy__options___policy__statement                             = _Action_policy__options + " " + _Action_policy__statement
	_Action_policy__options___prefix__list                                  = _Action_policy__options + " " + _Action_prefix__list
	_Action_policy__statement                                               = _Action_policy + "-" + _Action_statement
	_Action_pool                                             _Action        = "pool"
	_Action_port                                             _Action        = "port"
	_Action_preference                                       _Action        = "preference"
	_Action_prefix                                           _Action        = "prefix"
	_Action_prefix__list                                                    = _Action_prefix + "-" + _Action_list
	_Action_prefix__list__filter                                            = _Action_prefix__list + "-" + _Action_filter
	_Action_prefix__name                                                    = _Action_prefix + "-" + _Action_name
	_Action_protocol                                         _Action        = "protocol"
	_Action_protocols                                                       = _Action_protocol + "s"
	_Action_protocols___bgp                                                 = _Action_protocols + " " + _Action_bgp
	_Action_proxy                                            _Action        = "proxy"
	_Action_proxy__arp                                                      = _Action_proxy + "-" + _Action(_Protocol_arp)
	_Action_qnh                                              _Action        = "qnh"
	_Action_qualified__next__hop                                            = "qualified-" + _Action_next__hop
	_Action_redistribute                                     _Action        = "redistribute"
	_Action_reject                                           _Action        = "reject"
	_Action_route                                            _Action        = "route"
	_Action_route__type                                                     = _Action_route + "-" + _Action_type
	_Action_routing                                          _Action        = "routing"
	_Action_routing__group                                                  = _Action_routing + "-" + _Action_group
	_Action_routing__instance                                               = _Action_routing + "-" + _Action_instance
	_Action_routing__instances                                              = _Action_routing__instance + "s"
	_Action_rule                                             _Action        = "rule"
	_Action_rule__set                                                       = _Action_rule + "-" + _Action_set
	_Action_security                                         _Action        = "security"
	_Action_security___address__book                                        = _Action_security + " " + _Action_address__book
	_Action_security___address__book___global                               = _Action_security___address__book + " " + _Action_global
	_Action_security___address__book___global___address                     = _Action_security___address__book___global + " " + _Action_address
	_Action_security___address__book___global___address__set                = _Action_security___address__book___global + " " + _Action_address__set
	_Action_security___nat                                                  = _Action_security + " " + _Action_nat
	_Action_security___nat___destination                                    = _Action_security___nat + " " + _Action_destination
	_Action_security___nat___proxy__arp                                     = _Action_security___nat + " " + _Action_proxy__arp
	_Action_security___nat___source                                         = _Action_security___nat + " " + _Action_source
	_Action_security___nat___static                                         = _Action_security___nat + " " + _Action_static
	_Action_security___policies                                             = _Action_security + " " + _Action_policies
	_Action_security___policies___global                                    = _Action_security___policies + " " + _Action_global
	_Action_security___policies___global___policy                           = _Action_security___policies___global + " " + _Action_security___policy
	_Action_security___policy                                               = _Action_security + " " + _Action_policy
	_Action_security__zone                                                  = _Action_security + "-" + _Action_zone
	_Action_security__zones                                                 = _Action_security__zone + "s"
	_Action_security__zones___security__zone                                = _Action_security__zones + " " + _Action_security__zone
	_Action_self                                             _Action        = "self"
	_Action_set                                              _Action        = "set"
	_Action_source                                           _Action        = "source"
	_Action_source__address                                                 = _Action_source + "-" + _Action_address
	_Action_source__address__name                                           = _Action_source__address + "-" + _Action_name
	_Action_source__nat                                                     = _Action_source + "-" + _Action_nat
	_Action_source__port                                                    = _Action_source + "-" + _Action_port
	_Action_source__prefix__list                                            = _Action_source + "-" + _Action_prefix__list
	_Action_st                                                              = _Action(_Type_st)
	_Action_statement                                        _Action        = "statement"
	_Action_static                                           _Action        = "static"
	_Action_static___route                                                  = _Action_static + " " + _Action_route
	_Action_static__nat                                                     = _Action_static + "-" + _Action_nat
	_Action_table                                            _Action        = "table"
	_Action_term                                             _Action        = "term"
	_Action_then                                             _Action        = "then"
	_Action_to                                               _Action        = "to"
	_Action_to___zone                                                       = _Action_to + " " + _Action_zone
	_Action_to__zone                                                        = _Action_to + "-" + _Action_zone
	_Action_type                                             _Action        = "type"
	_Action_vi                                               _Action        = "vi"
	_Action_zone                                             _Action        = "zone"
	_Action_zones                                                           = _Action_zone + "s"
	_Communication_ptmp                                      _Communication = "ptmp"
	_Communication_ptp                                       _Communication = "ptp"
	_Mask_exact                                              _Mask          = "exact"
	_Mask_longer                                             _Mask          = "longer"
	_Mask_orlonger                                           _Mask          = "orlonger"
	_Name_AS                                                 _Name          = "AS"
	_Name_ID                                                 _Name          = "ID"
	_Name_PUBLIC                                             _Name          = "OUTER_LIST"
	_Name_any                                                _Name          = "any"
	_Name_fxp0                                                              = _Name(_Type_fxp) + "0"
	_Name_fxp0_0                                                            = _Name_fxp0 + ".0"
	_Name_gr0                                                               = _Name(_Type_gr) + "0"
	_Name_junos_host                                         _Name          = "junos-host"
	_Name_lo0                                                               = _Name(_Type_lo) + "0"
	_Name_lo0_0                                                             = _Name_lo0 + ".0"
	_Name_lt0                                                               = _Name(_Type_lt) + "0"
	_Name_master                                             _Name          = "master"
	_Name_mgmt_junos                                         _Name          = "mgmt_junos"
	_Name_st0                                                               = _Name(_Type_st) + "0"
	_Protocol_access_internal                                _Protocol      = "access-internal"
	_Protocol_aggregate                                      _Protocol      = "aggregate"
	_Protocol_ah                                             _Protocol      = "ah"
	_Protocol_all                                            _Protocol      = "all"
	_Protocol_arp                                            _Protocol      = "arp"
	_Protocol_bgp                                            _Protocol      = "bgp"
	_Protocol_direct                                         _Protocol      = "direct"
	_Protocol_egp                                            _Protocol      = "egp"
	_Protocol_esp                                            _Protocol      = "esp"
	_Protocol_gre                                            _Protocol      = "gre"
	_Protocol_icmp                                           _Protocol      = "icmp"
	_Protocol_icmp6                                          _Protocol      = "icmp6"
	_Protocol_igmp                                           _Protocol      = "igmp"
	_Protocol_ipip                                           _Protocol      = "ipip"
	_Protocol_local                                          _Protocol      = "local"
	_Protocol_ospf                                           _Protocol      = "ospf"
	_Protocol_pim                                            _Protocol      = "pim"
	_Protocol_rsvp                                           _Protocol      = "rsvp"
	_Protocol_sctp                                           _Protocol      = "sctp"
	_Protocol_static                                         _Protocol      = "static"
	_Protocol_tcp                                            _Protocol      = "tcp"
	_Protocol_udp                                            _Protocol      = "udp"
	_Route_Weight_bits_per_rm                                _Route_Weight  = 2
	_Route_Weight_max_rm                                                    = 32/_Route_Weight_bits_per_rm - 1
	_Service_all                                             _Service       = "all"
	_Service_any_service                                     _Service       = "any-service"
	_Service_bootp                                           _Service       = "bootp"
	_Service_dhcp                                            _Service       = "dhcp"
	_Service_dhcpv6                                          _Service       = "dhcpv6"
	_Service_ike                                             _Service       = "ike"
	_Service_ping                                            _Service       = "ping"
	_Service_snmp                                            _Service       = "snmp"
	_Service_snmp_trap                                       _Service       = "snmp-trap"
	_Service_ssh                                             _Service       = "ssh"
	_Service_traceroute                                      _Service       = "traceroute"
	_Type_destination                                        _Type          = "destination"
	_Type_exact                                              _Type          = "exact"
	_Type_firewall                                           _Type          = "firewall"
	_Type_fqdn                                               _Type          = "fqdn"
	_Type_from                                               _Type          = "from"
	_Type_fxp                                                _Type          = "fxp"
	_Type_global                                             _Type          = "global"
	_Type_gr                                                 _Type          = "gr"
	_Type_ipprefix                                           _Type          = "ipprefix"
	_Type_internal                                           _Type          = "internal"
	_Type_external                                           _Type          = "external"
	_Type_lo                                                 _Type          = "lo"
	_Type_lt                                                 _Type          = "lt"
	_Type_policy_statement                                   _Type          = "policy-statement"
	_Type_pool                                               _Type          = "pool"
	_Type_set                                                _Type          = "set"
	_Type_source                                             _Type          = "source"
	_Type_st                                                 _Type          = "st"
	_Type_static                                             _Type          = "static"
	_Type_then                                               _Type          = "then"
	_Type_to                                                 _Type          = "to"

	_group                _Default = "settings_group"
	_loglevel             _Default = "settings_loglevel"
	_sp_default_policy    _Default = "settings_sp_efault_policy"
	_comm_if              _Default = "settings_comm_if"
	_comm_vi              _Default = "settings_comm_vi"
	_VI_IPPrefix          _Default = "settings_VI_IPprefix"
	_VI_IPShift           _Default = "settings_VI_IPshift"
	_RI                   _Default = "settings_RI"
	_mgmt_RI              _Default = "settings_mgmt_RI"
	_mgmt_IF              _Default = "settings_mgmt_IF"
	_host_RI              _Default = "settings_host_RI"
	_mgmt_Description     _Default = "settings_mgmt_description"
	_domain_name          _Default = "settings_domain_name"
	_GT_list              _Default = "settings_GT_list"
	_dirname_GT           _Default = "settings_path_GT"
	_dirname_out          _Default = "settings_path_out"
	_filename_host_list   _Default = "settings_filename_host_list"
	_filename_list_config _Default = "settings_files_config"
	// _Route_Weight_bits_per_rm       _Default = "settings_Route_Weight_bits_per_rm"
	// _Route_Weight_max_rm           _Default = "settings_Route_Weight_max_rm"
)
